### ISSUE TITLE
Timeout configuration

### ISSUE THREAD

**Issue by ThaDafinser** [TQsoft-GmbH/mod_authn_ntlm#19]
Hello,

is it possible to configure a timeout? Just had the case that a NTLM service was hanging "forever".

**Comment by YvesR** [comment]
As far as I know there is not such a configuration parameter. All parameters are list in the readme.md.
What do you mean with hanging forever in detail?

**Comment by YvesR** [comment]
Do you have more information you can provide about your timeout problem or is this issue obsolete?

**Comment by ThaDafinser** [comment]
Sadly i have not more informations.

The case was, that the ActiveDirectory server had a complete hang and this NTLM module did not timed out after a period of time - it waited forever.
