### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by ahai1980** [TQsoft-GmbH/mod_authn_ntlm#28]
Hi,
i get the error

This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
in httpd.conf

```
Alias /test "/var/www/html/test"

<Directory "/var/www/html/test">
    Authtype CAS
    require valid-user
    Options Indexes MultiViews
    AllowOverride all
    Order allow,deny
    Allow from all
</Directory>
```

thanks

**Comment by YvesR** [comment]
Please read the example configuration.
You want to use this module using `sspi` but have the wrong `Authtype` set.
If still get not solve it please post more details after.
