### ISSUE TITLE
Cannot start the server after loading the ntlm module

### ISSUE THREAD

**Issue by shivamspj** [TQsoft-GmbH/mod_authn_ntlm#34]
I am using Apache VC 15 2.4. As soon as I load module the Apache server cannot restart at all.

**Comment by YvesR** [comment]
Did you compile the SO file with the correct compiler then that fits to your installation (Version and 32/64bit)?

**Comment by ckayfish** [comment]
What is the .so file included in the download's /bin folder? Is there anywhere to get a pre-compiled 64bit version?

**Comment by YvesR** [comment]
I don't know for sure what version the .so file is. As we are using 64bit it should be 64 bit as well, but we do not deliver compiled version, therefor we made a read me with details how to compile and as @JBlond mentioned ApacheHaus does this job very well.

**Comment by ckayfish** [comment]
I was using the most recent 64bit ApacheHaus dist for 2.4.x, but forgot they had modules separate from the main release. Found a working copy here: https://www.apachehaus.com/cgi-bin/download.plx
