### ISSUE TITLE
Sample Config Error

### ISSUE THREAD

**Issue by tomrade** [TQsoft-GmbH/mod_authn_ntlm#35]
the commented out group line in the sample config shows 

```#require sspi-user EMEA\group_name```

but it should be 

```#require sspi-group EMEA\group_name```

Nothing major, just caught me out , maybe have two lines for both sspi-group an sspi-user

**Comment by JBlond** [comment]
Good catch! I opened a PR https://github.com/TQsoft-GmbH/mod_authn_ntlm/pull/36
