### ISSUE TITLE
AppVeyor automatic build

### ISSUE THREAD

**Issue by alphp** [TQsoft-GmbH/mod_authn_ntlm#38]
Hi, I have worked to create the AppVeyor automatic build script.

For the moment I have learned how to handle CMake to create the different versions and I have managed to compile a Release correctly.

The idea is that the script construates the x86 / x64 versions in both Debug and Release mode.

Regards

**Comment by alphp** [comment]
Pull requests #39 
Script for automatic build is ready.

**Comment by YvesR** [comment]
Hello @alphp ,
did you setup this also in AppVeyor? I have close to no experience with it, but it would be nice if we can setup this as automatic test for this project if you already invested the time (which I do appreciate).
Yves

**Comment by alphp** [comment]
The script is only to build the binaries. I do not have a compiler, so I use AppVeyor to get those binaries I need.

I know that AppVeyor can be used to perform test operation, in that case you could check if apache is able to start with the generated binaries, I do not know if authentication could also be tested.

Anyway, I do not have experience in the creation of tests. A little more than a year ago I discovered AppVeyor and I have learned enough to fight with the compilation scripts, nothing more.

With [InExtenso/win32service](https://github.com/InExtenso/win32service) I just create the construction script and it was wonderful because it allowed to have binaries of each Push automatically, ready so that those involved and interested could test if everything worked as it should.

**Comment by YvesR** [comment]
ok, I do understand. I will look into it and come back to you on your PR asap.

**Comment by YvesR** [comment]
Merged it.
