### ISSUE TITLE
Cannot offer both basic and ntlm

### ISSUE THREAD

**Issue by f-w** [TQsoft-GmbH/mod_authn_ntlm#41]
When setting `NTLMOfferBasic On` and run `curl -k --basic  -u user:pswd https://mysite`. I got 401 unauthorized error. Error on server is `[Thu Feb 21 09:35:43.432826 2019] [auth_ntlm:error] [pid 9748:tid 940] [client xxx.xxx.xxx.xxx:57889] client used wrong authentication scheme: (null) for /<path>/ (needed NTLM)`.
If switching curl option from --basic to --ntlm, it works.
By contrast mod_auth_sspi handles both ntlm and basic correctly.

**Comment by YvesR** [comment]
@f-w Hi, problem fixed by one of our devleopers, have fun :)

**Comment by ricardocedex** [comment]
Hello, 
  I have seen that you have resolved this issue, did you upload x64 and win32 binaries? The ones I found in Apache Haus are, I think, from 2017? Thanks for the help!

**Comment by JBlond** [comment]
@ricardocedex I'm from ApacheHaus and we have the last released from from https://github.com/TQsoft-GmbH/mod_authn_ntlm/releases . If there is a new release we can build it.

**Comment by ricardocedex** [comment]
Thanks for your answer,


 I was looking at releases and they don´t match. In  https://github.com/TQsoft-GmbH/mod_authn_ntlm/releases they talk about: stable-1.0.1-32/64bit

However in ApacheHaus there is a mod_authn_ntml-1.0.8-2.4.x-x64-vc14.zip  so I got confused about versions. If you say that they are the same I believe you! There has been also some changes in the module but it´s true that they haven´t release a new stable version.


Thanks!

Ricardo


Ricardo Herrero Santos
Jefe de Área de Ingeniería de Sistemas
CENTRO DE ESTUDIOS HIDROGRÁFICOS - CEDEX
GoogleMaps: https://goo.gl/maps/iRAFNpRqNA8dUVmGA
Paseo Bajo Virgen del Puerto s/n
C.P.: 28005
Teléfono: +34 91 335 80 32
correo: ricardo.herrero@cedex.es<mailto:ricardo.herrero@cedex.es>
________________________________
De: Mario <notifications@github.com>
Enviado: viernes, 3 de abril de 2020 8:27:29
Para: TQsoft-GmbH/mod_authn_ntlm
Cc: Ricardo Herrero Santos; Mention
Asunto: Re: [TQsoft-GmbH/mod_authn_ntlm] Cannot offer both basic and ntlm (#41)


@ricardocedex<https://github.com/ricardocedex> I'm from ApacheHaus and we have the last released from from https://github.com/TQsoft-GmbH/mod_authn_ntlm/releases . If there is a new release we can build it.

**Comment by TQjona** [comment]
Hello,

we tagged a new release, including the bug fix for this issue.

See: https://github.com/TQsoft-GmbH/mod_authn_ntlm/releases/tag/stable-1.0.2
