### ISSUE TITLE
problematic www-Authenticate list if NTLMBasicPreferred is set

### ISSUE THREAD

**Issue by chrisbald** [TQsoft-GmbH/mod_authn_ntlm#42]
if both options, NTLMOfferBasic and NTLMBasicPreferred is set, the www-Authenticate list contains two different Basic entries
`WWW-Authenticate: Basic realm="My Realm"`
`WWW-Authenticate: Basic`
This setting seems to be handled gracefully by Firefox, but the Apache serf library will choke on that and crash due to a null pointer access as it expects a "realm=" string in the second authenticate entry.

I would expect the list to be like:
`WWW-Authenticate: Basic realm="My Realm"`
`WWW-Authenticate: NTLM`
which is generated by the old mod_auth_sspi module.

This behavior seems to be generated in mod_ntlm_authentication.c by
`if (ctx.crec->sspi_offerbasic && ctx.crec->sspi_basicpreferred) ctx.crec->sspi_packages = "Basic";` (Line 700 in version 1.01)

If this instruction is removed, the expected list will be generated.

**Comment by YvesR** [comment]
@chrisbald Problem fixed by one of our developers. Have fun.
