### ISSUE TITLE
error when trying to start apache

### ISSUE THREAD

**Issue by tguichard25** [TQsoft-GmbH/mod_authn_ntlm#44]
Hello, 

I have an error when I start apache 2.4
invalid ELF header

**Comment by JBlond** [comment]
Did you compile it yourself? Or where did you download the binary?

**Comment by tguichard25** [comment]
Download from https://github.com/TQsoft-GmbH/mod_authn_ntlm/tree/master/bin

**Comment by neongrau** [comment]
The module is for windows only. It cannot be used on Linux.
