### ISSUE TITLE
mod_authn_ntlm.so ECF Header invalid

### ISSUE THREAD

**Issue by mazero** [TQsoft-GmbH/mod_authn_ntlm#49]
I have my config make with a dockerfile and I copy the file so to folder module and when I generate my container, my config with the LoadModule doesn't work. 
In the logs and on the server I find my file modules/mod_authn_ntlm.so but I have this message error **"modules/mod_authn_ntlm.so ECF Header invalid"**

I have apache 2.4, Debian.
Do you have any ideas ?

**Comment by YvesR** [comment]
Hello. 
This module works on Windows only!

**Comment by mazero** [comment]
Thx. Do you have an ideas that I must use to have NTML with Linux ?

**Comment by YvesR** [comment]
So far I know on linux u can only use mod ldap module. but this will be basic auth using SSL
