### ISSUE TITLE
Version in source vs release number

### ISSUE THREAD

**Issue by JBlond** [TQsoft-GmbH/mod_authn_ntlm#50]
In the source code there is

```C
#define MOD_NTLM_VERSION_MAJOR 1
#define MOD_NTLM_VERSION_MID 0
#define MOD_NTLM_VERSION_MINOR 7
```

while the last release on github is 1.0.2

What is the correct number?

**Comment by JBlond** [comment]
Also mind, that the 1.0.7 changed 2 years ago in the source code. It is hard to explain to the people on ApacheHaus that they shall upgrade from 1.0.7 to 1.0.2. That makes no sense.

**Comment by YvesR** [comment]
@JBlond Hi Mario, wenn my guess is that versions got messed up. As you know we took over the code and fixed and enhanced it from previous project. Will look into it later and update.
